### ISSUE TITLE
Promote deployment to production via deployctl

### ISSUE THREAD

**Issue by javdl** [denoland/deployctl#142]
Deployment works great for me, I can push a site to Deno Deploy without issue (via GitLab CI). However, there's one step missing from deployctl as far as I can tell that I couldn't find in the -h or readme, which is to **promote to production**.
When I have merged a branch to main branch, I want to deploy it (works) but then I can not promote it to production via CLI, effectively disabling me to fully deploy to production via CI.
Is this something you're planning to support or am I missing something?

**Comment by andrewbrey** [comment]
@Joostvanderlaan I don't think there's the ability to _promote a preview build to production_ but you can run your `deployctl deploy` command with the `--prod` flag to deploy right to production, e.g.:

```sh
deployctl deploy --project my-project-name --prod server.ts
```

**Comment by javdl** [comment]
Thank you Andrew, works like a charm!
