### ISSUE TITLE
Deploying static folders with spaces fails

### ISSUE THREAD

**Issue by rajsite** [denoland/deployctl#150]
When I try to deploy my deno app to deno deploy it fails with error:

```
error: The deployment failed: Module not found "file:///src/My%20Server/server.ts".
```

I simplified the test case and believe the issue is having spaces in folder names. I have a folder structure like the following:

```
/src
  /My Client
    index.html
  /My Server
    server.ts
```

I run the `deployctl` command from the `src` directory so that both the `My Client` and `My Server` directories are uploaded as static content.

I can run the `deno -A "./My Server/server.ts"` command successfully from the `src` directory and my application is able to serve the static content of the `My Client` directory just fine.

If I do a `--dry-run` publish with `deployctl deploy "./My Server/server.ts" "--dry-run" "--project=<MY_PROJECT>" "--token=<MY_TOKEN>"` from the `src` directory it completes successfully:

```
i Performing dry run of deployment
√ Project: <MY_PROJECT>
i Uploading all files from the current dir (C:\<MY_PATH>\src)
√ Found 2 assets.
√ No new assets to upload.
```

If I do a publish with `deployctl deploy "./My Server/server.ts" "--project=<MY_PROJECT>" "--token=<MY_TOKEN>"` from the `src` directory it fails with the error above, full log:

```
√ Project: <MY_PROJECT>
i Uploading all files from the current dir (C:\<MY_PATH>\src)
√ Found 2 assets.
√ No new assets to upload.
× Deployment failed.
error: The deployment failed: Module not found "file:///src/My%20Server/server.ts".
```

Versions:
```
deployctl 1.5.0
deno 1.31.3 (release, x86_64-pc-windows-msvc)
v8 11.0.226.19
typescript 4.9.4
```

OS: Windows 11 22H2 Build 22621.819

Attached is the minimal reproduction: [issue.zip](https://github.com/denoland/deployctl/files/10996496/issue.zip)

**Comment by lucab** [comment]
@rajsite thanks for the report. Indeed this looks like a backend bug, and we are currently looking into it. I'm thus closing this ticket in favor of https://github.com/denoland/deploy_feedback/issues/348.
