### ISSUE TITLE
Asset folder contents not uploaded

### ISSUE THREAD

**Issue by mxdvl** [denoland/deployctl#164]
Recently, my `build` folder for a static website has failed to upload. [Link to run with debug](https://github.com/mxdvl/mononykus/actions/runs/5518348185/jobs/10062236676).

<img width="596" alt="image" src="https://github.com/denoland/deployctl/assets/76776/a64dd993-20b2-4a63-8a6e-39a0e051adff">

Could this be a duplicate of #100?

**Comment by kt3k** [comment]
Is `root` setting in `denoland/deployctl` action accurate?

```yaml
  root: file:///tmp/build
```

**Comment by mxdvl** [comment]
> Is `root` setting in `denoland/deployctl` action accurate?
> 
> ```yaml
>   root: file:///tmp/build
> ```

I’ve tried a series of permutations, none of them work.

- `build` (this what what it used to be and worked fine)
- `./build`
- `file:///tmp/build`

**Comment by kt3k** [comment]
When I run `deno task build` in the repo ( https://github.com/mxdvl/mononykus ), I got `build/index.html` with contents `[object Promise]`. I think there's something wrong in `src/build.ts`
