### ISSUE TITLE
error: Uncaught (in promise) NotFound: Failed to spawn 'start': program not found

### ISSUE THREAD

**Issue by LeonnardoVerol** [denoland/deployctl#254]
I am having this problem

`error: Uncaught (in promise) NotFound: Failed to spawn 'start': program not found`

cmd I am running:
`deployctl deploy --project=xxxxx --entrypoint=src/main.ts `

If I run just `deployctl deploy` I get this other msg: 
```
× Guessing project name 'test': Creating project...
error: ENOENT
```

My Deploy CLI Version: `1.10.3`

And I see another [person with the same problem on  StackOverflow](https://stackoverflow.com/questions/77890617/error-uncaught-in-promise-notfound-failed-to-spawn-start-program-not-foun)

**Comment by LeonnardoVerol** [comment]
Follow up: Refreshing my token worked.

**Comment by arnauorriols** [comment]
Hey, thanks for the report, and helping out in StackOverflow.

Could you tell us a bit about your environment, particularly what command-line shell are you using?

**Comment by LeonnardoVerol** [comment]
> Hey, thanks for the report, and helping out in StackOverflow!
> 
> Could you tell us a bit about your environment, particularly what command-line shell are you using?

- Windows 11 Pro (Version 10.0.22631 Build 22631)
- deno 1.40.3
- deployctl 1.10.3
- Windows Terminal Version: 1.18.3181.0 (Running Powershell as default from  %SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe )

Refresh Token cmd used: `$env:DENO_DEPLOY_TOKEN = 'your_access_token_here'`

**Comment by arnauorriols** [comment]
TBH I'm not super familiar with the windows environment, but I was testing in a windows server machine with Powershell and the `start` command is aliased to `Start-Process` there. Can you confirm in your Powershell you can execute `Start-Process https://deno.com`?
