### ISSUE TITLE
can not deploy from URL

### ISSUE THREAD

**Issue by ije** [denoland/deployctl#26]
<img width="972" alt="Screen Shot 2021-03-30 at 11 21 44 PM" src="https://user-images.githubusercontent.com/2883484/113013923-ba3f9c00-91ae-11eb-804a-752ffff87c9a.png">

url: https://raw.githubusercontent.com/postui/og-image/main/og-image.ts
repo: https://github.com/postui/og-image

deployctl works fine on my computer:

<img width="1648" alt="Screen Shot 2021-03-30 at 11 25 19 PM" src="https://user-images.githubusercontent.com/2883484/113014484-33d78a00-91af-11eb-934b-6833081d00af.png">

**Comment by lucacasonato** [comment]
https://raw.githubusercontent.com/postui/og-image/main/og-image.ts is 404 for me.

**Comment by lucacasonato** [comment]
We have found the issue. A fix should be rolling out in the next couple of hours.

**Comment by ije** [comment]
sorry i renamed: https://raw.githubusercontent.com/postui/og-image/main/og-image.js

**Comment by ije** [comment]
deployctl is OK:
```base
deployctl run https://raw.githubusercontent.com/postui/og-image/main/og-image.js
```

**Comment by lucacasonato** [comment]
The issue has been resolved.

**Comment by ije** [comment]
thanks
