### ISSUE TITLE
How to deploy SPA to deno.com?

### ISSUE THREAD

**Issue by RastaAlex** [denoland/deployctl#27]
I [read that I can deploy SPA](https://deno.com/deploy/docs/fair-use-policy), but I see that [API Reference](https://deno.com/deploy/docs/runtime-api) has no `Deno.open`.
`deployctl check mode.ts` says the same, and `deno.com` as well for such code:

```ts
import { urlParse } from 'https://deno.land/x/url_parse/mod.ts';

addEventListener('fetch', (event: FetchEvent) => {
    event.respondWith(handleRequest(event.request));
});

async function handleRequest(request: Request) {
    const okFile = Deno.open(import.meta.url);

    const resultResponse = new Response(null, {
       headers: {
          body: okFile,
        },
    });

    return resultResponse;
}
```

Could you please tell me how can I serve `static files`, like `style` and `images`?  

**EDIT**: Maybe related to https://github.com/denoland/deployctl/issues/20.

**Comment by satyarohith** [comment]
> Could you please tell me how can I serve static files, like style and images?

Here's a small guide: https://deno.com/deploy/docs/serve-static-assets

>  const okFile = Deno.open(import.meta.url);

You cannot use `Deno.open` on Deploy.  Visit https://deno.com/deploy/docs/runtime-api to checkout supported APIs.

**Comment by coderaiser** [comment]
When I try to run `mode.ts` using `deployctl` with content:

```ts
import { urlParse } from 'https://deno.land/x/url_parse/mod.ts';

addEventListener('fetch', (event: FetchEvent) => {
    event.respondWith(handleRequest(event.request));
});

async function handleRequest(request: Request) {
    return await fetch(import.meta.url);
}
```

I see:
```js
error: Uncaught (in promise) TypeError: scheme 'file' not supported
    return await fetch(import.meta.url);
                 ^
    at handleError (deno:core/core.js:186:12)
    at jsonOpParseResult (deno:core/core.js:356:9)
    at opSync (deno:core/core.js:259:32)
    at Object.jsonOpSync (deno:core/core.js:372:12)
    at opFetch (deno:op_crates/fetch/26_fetch.js:887:17)
    at sendFetchReq (deno:op_crates/fetch/26_fetch.js:1257:44)
    at fetch (deno:op_crates/fetch/26_fetch.js:1379:31)
    at handleRequest (file:///Users/coderaiser/thecat/mod.ts:8:18)
    at file:///Users/coderaiser/thecat/mod.ts:4:23
    at innerInvokeEventListeners (deno:op_crates/web/02_event.js:750:27)
error: Process exited with code 1
```

I can't serve static locally for now? When deploying everything works good.

**Comment by kt3k** [comment]
@coderaiser serving local static file is not supported yet, but we are working on it at #23

**Comment by lucacasonato** [comment]
Thanks for contributing by opening an issue.

This project is being archived because you can now use `deno run` to run your Deploy scripts locally: https://deno.com/deploy/docs/running-scripts-locally/. As such, I will close this issue.

If you have feedback about Deno Deploy, please open an issue on this repo: https://github.com/denoland/deploy_feedback
