### ISSUE TITLE
deployctl is not able to read env secret in GitHub Action

### ISSUE THREAD

**Issue by iShibi** [denoland/deployctl#298]
I have set the Deno Deploy access token as `DENO_DEPLOY_TOKEN` on GitHub and I still get this error:

```
Entrypoint: file:///src/main.ts
Error: APIError: The authorization token is not valid.
```

**Comment by magurotuna** [comment]
Can you share your GitHub Actions workflow file? Also, setting `DENO_DEPLOY_TOKEN` is not required in most cases, as described in https://github.com/denoland/deployctl/blob/main/action/README.md#usage:

> You do not need to set up any secrets for this to work.
>
> You do need to link your GitHub repository to your Deno Deploy project. You have to choose the "GitHub Actions" deployment mode in your project settings on https://dash.deno.com/. Read [Deno Deploy documenation](https://docs.deno.com/deploy/manual/ci_github#github-action) for more information.

Can you make sure to link your repository to the Deno Deploy project?

**Comment by iShibi** [comment]
Okay, it's working now. Here is what I did:

1. I went to project settings in Deno Deploy and changed git integration from "Automatic" to "Github Action". This created a new "Production" environment on my repo.
2. I created an env secret "DENO_DEPLOY_TOKEN" in this "Production" environment and saved the access token in it.

**Comment by magurotuna** [comment]
Glad to hear that you got it working. Closing as it's resolved, feel free to reopen or create a new issue if there's another question.

**Comment by justinmchase** [comment]
This is happening to me too, why do I have a `Production` environment when I'm trying to do a nonprod deploy? Also where do I get a `DENO_DEPLOY_TOKEN`? And the workflow isn't even set to use Production environment so how is that possible?
