### ISSUE TITLE
Memory limit exceeded on request

### ISSUE THREAD

**Issue by ije** [denoland/deployctl#30]
<img width="445" alt="Screen Shot 2021-04-01 at 2 37 31 PM" src="https://user-images.githubusercontent.com/2883484/113253491-e450a580-92f7-11eb-9b2c-9c6fd1abf3fa.png">

deploy URL: https://raw.githubusercontent.com/postui/og-image/main/og-image.js
deno.com: https://og-image.deno.dev/hello%20deno%20land

it seems deno.com doesn't allocate enough memory for each request to support CanvasKit in WebAssembly that is used by this case to draw a canvas image output.

**Comment by bnoordhuis** [comment]
There's a 128 MB memory limit.

You're allowed to go over the limit for a few milliseconds in case you have a burst-y workload (that's what "on probation" means) but if you stay over it, the process gets terminated.

**Comment by ije** [comment]
@bnoordhuis i think 128mb is enough in this case, can you please have a look? thanks!
https://github.com/postui/og-image

**Comment by lucacasonato** [comment]
It's not enough, otherwise you would not be hitting the limit.

**Comment by ije** [comment]
@lucacasonato i see, thanks! will try the commercial version when it is available
