### ISSUE TITLE
DNS error when trying to install @deno/deployctl

### ISSUE THREAD

**Issue by lauridskern** [denoland/deployctl#308]
When running deno install -Arf jsr:@deno/deployctl I get the following error:

`error: Import 'https://registry-staging.deno.com/@deno/deployctl/meta.json' failed: error sending request for url (https://registry-staging.deno.com/@deno/deployctl/meta.json): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known`

I am not using a proxy.

**Comment by chapoteaud** [comment]
Similar error as well when trying to install deployctl. Tried the following: 

1.  `deno install -Arf https://deno.land/x/deploy/deployctl.ts` 
Warning Implicitly using latest version (1.12.0) for https://deno.land/x/deploy/deployctl.ts
**error: Import 'https://registry-staging.deno.com/@std/path/meta.json' failed: error sending request for url (https://registry-staging.deno.com/@std/path/meta.json): error trying to connect: dns error: failed to lookup address information: Name or service not known**
2. `deno install -A jsr:@deno/deployctl`
**error: Import 'https://registry-staging.deno.com/@deno/deployctl/meta.json' failed: error sending request for url (https://registry-staging.deno.com/@deno/deployctl/meta.json): error trying to connect: dns error: failed to lookup address information: Name or service not known**

**Comment by chapoteaud** [comment]
Follow-up: Got my error working by upgrading Deno to 1.42.1. Install was successful and had to manually add to path variable. Hope this helps someone else

**Comment by magurotuna** [comment]
That DNS error happens when your Deno version is old. As @chapoteaud pointed out, upgrading Deno to 1.41.1+ (the latest version, 1.42.4 as of now, is generally recommended though) should solve the issue.

I feel the minimum required Deno version would be nice to have in readme to avoid confusion - just opened a PR for this #309
