### ISSUE TITLE
Version flag alias is capitalized

### ISSUE THREAD

**Issue by crqra** [denoland/deployctl#33]
I'm not sure this is an issue or it's meant to be like this, but the alias for `--version` flag is a capital `-V` instead of `-v` which seems like a typo.

I can submit a PR to fix it in case it's indeed a typo.

**Comment by lucacasonato** [comment]
This is not a typo. Lowercase -v is for verbose (which we have not implemented yet).

**Comment by crqra** [comment]
Nice to know! Thanks!
