### ISSUE TITLE
'readFileSync' does not exist on type 'typeof Deno'.

### ISSUE THREAD

**Issue by vilbergs** [denoland/deployctl#35]
Hey!

Sorry for the shallow post, I'm rather new in the world of Deno.

I've been utilizing deployctl to develop an API service that uses [dotenv](https://deno.land/x/dotenv@v2.0.0) for storing secret tokens.

Every time i import the library and run ` deployctl run --libs=ns,fetchevent ./index.ts` I get the following error:

```
Check file:///Users/user/sites/vilbergs/repo/$deno$eval.ts
error: TS2339 [ERROR]: Property 'readFileSync' does not exist on type 'typeof Deno'.
    return parse(new TextDecoder("utf-8").decode(Deno.readFileSync(filepath)));
                                                      ~~~~~~~~~~~~
    at https://deno.land/x/dotenv@v2.0.0/mod.ts:76:55

TS2339 [ERROR]: Property 'errors' does not exist on type 'typeof Deno'.
    if (e instanceof Deno.errors.NotFound) return {};
                          ~~~~~~
    at https://deno.land/x/dotenv@v2.0.0/mod.ts:78:27
```

Here is the [source repo](https://github.com/vilbergs/homebase-api). The examples above are slightly altered from the source to keep things agnostic to the purpose of my api.

**Comment by satyarohith** [comment]
[Deno Deploy](https://deno.com/deploy) doesn't have a file system and hence has no support for fs-related APIs. Check out [the docs](https://deno.com/deploy/docs/runtime-api) for supported APIs. 

For your use case, you can try `--env=.env-EXAMPLE` flag of `deployctl run` to load environment variables from your `.env` file instead of `dotenv` for local development.

**Comment by vilbergs** [comment]
Hey @satyarohith!

Thanks for the reply! That makes a lot of sense! I assumed there was perhaps a small cache / virtual fs as some other serverless environments provide, also since my code ran smoothly with the `--no-check` flag.

I'll go with your advice as I won't be dealing with a lot of secrets. Thanks :D
