### ISSUE TITLE
Set Deno.noColor attr to false

### ISSUE THREAD

**Issue by cknight** [denoland/deployctl#36]
I maintain a logging library and like most logging libraries (including `std/log`) it imports various colors from `/std/fmt/colors.ts`.  My library is built to not use colors when they are not available, via `Deno.noColor`.  

However, when I import my library into a deno deploy script, I get this error when running `deployctl check` on it:
```
error: TS2339 [ERROR]: Property 'noColor' does not exist on type 'typeof Deno'.
const noColor = globalThis.Deno?.noColor ?? true;
                                 ~~~~~~~
    at https://deno.land/std@0.92.0/fmt/colors.ts:15:34
```
Simple reproduction by running `deployctl check mod.ts` with mod.ts as follows:
```
import { blue } from "https://deno.land/std@0.92.0/fmt/colors.ts";

addEventListener("fetch", (event) => {
    const response = new Response("Hello World!", {
      headers: { "content-type": "text/plain" },
    });
    event.respondWith(response);
  });
```

A simple fix would be to set `Deno.noColor = false` I believe.

**Comment by lucacasonato** [comment]
This is now resolved. You can upgrade your deployctl with `deployctl upgrade`.
