### ISSUE TITLE
Every second request hangs with simple proxy worker example

### ISSUE THREAD

**Issue by lucidNTR** [denoland/deployctl#49]
i encounter a weird bug in deployctl (i tested using deno 1.9.2  and 1.9.1  and deployctl 0.3.0 on apple M1 and on intel build)
when i run a simple worker like this:
deployctl run  --reload --no-check --addr=:8086 script.js

script.js :
```
self.addEventListener("fetch", (event) => {
  event.respondWith(fetch('http://google.com'))
});
```

every second request to the endpoint hangs and only when i cancel the request client side, then the next request works again and so on.
this only happens if i do the requests from chrome or insomnia, but not with curl as cli, which might point to an issue with connection reuse, i inspected the headers that chrome and insomnia use vs the curl cli ones but could not find a suspicious difference.

the bug could also be reproduced with a different local webserver.

the same behaviour is shown if i use https://deno.land/x/fetch_event_adapter@v0.3.3/listen.ts with the same worker code, which is a completely different implementation but also uses Deno.serveHttp, so this might point to a bug in deno.

possible connection to: deno issue #10182

**Comment by lucidNTR** [comment]
same behaviour if i await the fetch first and then try constructiong a new response object from the result manually.

**Comment by lucidNTR** [comment]
still present in deno 1.10.1

**Comment by lucidNTR** [comment]
could someone reproduce this yet/ validate if the bug is in deno or denoctl ?

**Comment by wperron** [comment]
Works for me on Ubuntu 20.10 + Deno 1.10.1 + Deployctl 0.3.0 -- what version of deployctl are you running?

**Comment by lucidNTR** [comment]
@wperron  deployctl 0.3.0

ok thats a good lead, i will try reproducing with an ubuntu docker container.

**Comment by lucidNTR** [comment]
@wperron i just reproduced the bug in a completely fresh ubuntu environment on github codespaces.

Linux version 5.4.0-1047-azure (buildd@lgw01-amd64-050) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #49~18.04.1-Ubuntu

<img width="1530" alt="Screenshot 2021-06-09 at 22 00 23" src="https://user-images.githubusercontent.com/1176068/121421135-21778a80-c96e-11eb-8c86-e30e3fb16eb0.png">

**Comment by lucidNTR** [comment]
I am setting up a bounty of 350$ for a resolution.

**Comment by lucidNTR** [comment]
the bug seems to be not present on deno deploy, here is a production published endpoint 

https://dark-duck-39-0301fc2f.deno.dev

**Comment by lucidNTR** [comment]
update: confirmed relation to connection reuse:
curl http://localhost:8086/ http://localhost:8086/ triggers the same bug

however 
curl http://localhost:8086/
curl http://localhost:8086/

does not show the problem

**Comment by lucacasonato** [comment]
You can likely work around the bug by setting `connection: close` header.

**Comment by lucidNTR** [comment]
@lucacasonato  yes that would at least be the first possible workaround ( : ) ), but i would need to make all handlers async, change headers, reconstruct the response object or is there a way i can do this without changing handler functions?

**Comment by lucacasonato** [comment]
There is not.

**Comment by bartlomieju** [comment]
This is a problem in HTTP bindings in Deno, will be fixed by https://github.com/denoland/deno/pull/10923

**Comment by lucidNTR** [comment]
confirmed denoland/deno#10923 fixes the issue. thank you!!
