### ISSUE TITLE
Running `deployctl` using --unstable

### ISSUE THREAD

**Issue by Schotsl** [denoland/deployctl#52]
Hey! I'm trying out Deno Deploy and wanted to connect to a MySQL database, when I important and construct the `Client` class from the `mysql` third-party package. I get notifified that certain properties don't exists on the Deno instance and that I might want to use the `--unstable` flag.

So I figured same old, same old and added `--unstable` but this threw an error. After I checked out the help text I noticed that there isn't an option for the unstable flag, Does this mean that it's impossible to run packages that require `--unstable` using Deno Deploy? I figure this will cross of alot of packages from being compatible with the hosting service

**Comment by satyarohith** [comment]
> Does this mean that it's impossible to run packages that require --unstable using Deno Deploy?

Yes. Check out https://deno.com/deploy/docs/runtime-api for supported APIs.

**Comment by almereyda** [comment]
More context, in case anyone else wonders:

* https://github.com/denoland/deno/discussions/13607
* https://github.com/denoland/deploy_feedback/issues/22
