### ISSUE TITLE
bug: local files are not intact when served

### ISSUE THREAD

**Issue by satyarohith** [denoland/deployctl#60]
Steps to reproduce.

1. Download an image.
```sh
curl https://raw.githubusercontent.com/nonstdout/deno-deploy/main/smiley.png > smiley.png
```
2. Run this script.
```js
addEventListener("fetch", (event) => {
  event.respondWith(fetch(new URL("./smiley.png", import.meta.url)));
});

```
3. Download the image again from the local server.
```sh
curl localhost:8080 > new.png
```
Try to open the `new.png`, and you'll see it being corrupted.

Edit:
Versions: deployctl from `main` and `deno 1.11.0`

**Comment by lucacasonato** [comment]
This should already be fixed on the main branch.
