### ISSUE TITLE
Listening on http://0.0.0.0:8080 not working

### ISSUE THREAD

**Issue by nhrones** [denoland/deployctl#63]
When I run the examples in Win10, the terminal says _Listening on http://0.0.0.0:8080_
This shows 'This site can’t be reached' error in chrome.
If instead I browse to localhost:8080 I get the 'hello world'
Also, http://127.0.0.1:8080 works fine.

deno 1.11.3
deployctl 0.3.0

**Comment by wperron** [comment]
We can probably just change the line printed to the console to say `localhost` instead of `0.0.0.0` as that also works on Linux and MacOS, and I suspect is what most people will use anyway.

**Comment by nhrones** [comment]
This is something I could tackle.  I don't have much experience with git.  How can I learn to contribute?

**Comment by nhrones** [comment]
Also, Deno ... new URL() has a major issue at least on Win10. Where  should I report this?

**Comment by satyarohith** [comment]
> This is something I could tackle. I don't have much experience with git. How can I learn to contribute?

This can help you: https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github

**Comment by wperron** [comment]
Hi @nhrones thanks for your interest! If Git and Github are pretty new to you, I recommend [GitHub's learning material](https://docs.github.com/en/get-started) it's pretty good and covers a lot of ground. If you have specific issues, don't hesitate to contact me directly, I'm always happy to help.

As for the `new URL()` issue, that would probably go on the [denoland/deno](https://github.com/denoland/deno) repo, though it might be a good idea to bring it up on the [Discord server](https://diszord.gg/deno) first

**Comment by nhrones** [comment]
in Chrome-v8 ...
```
<script>
    	console.log(new URL("c:/docs", "file:///"))
</script>
```
returns      **file:///C:/docs**

in Deno ... 
```
	console.log(new URL("c:/docs", "file:///"))
```
returns      **c:/docs**

This was a big issue in trying to run deployCtl on Ein 10
If Deno URL not browser compat? I can see this creating many ;Deno-Windows; Issues!

**Comment by nhrones** [comment]
Read docs ... watch videos ... still couldn't create a new pull request.  Getting to old(73) I guess.  Wish I could contribute.

**Comment by wperron** [comment]
> Read docs ... watch videos ... still couldn't create a new pull request. Getting to old(73) I guess. Wish I could contribute.

You'll need to fork the repository and push your changes to your fork first. We can take this offline if you prefer, that way we don't spam the issue with comments. Feel free to email me at hey@wperron.io
