### ISSUE TITLE
captureStackTrace does not exist on type ErrorConstructor

### ISSUE THREAD

**Issue by kyeotic** [denoland/deployctl#71]
deployctl produces typescript compilation errors when the `Error.captureStackTrace` is used along with `--libs=ns,fetchevent` ([see this](https://github.com/satyarohith/sift#usage) for why I am doing this).

```
deployctl run --libs=ns,fetchevent src/mod.ts
Check file:///Users/kyeotic/dev/brophylactic-bot/$deno$eval.ts
error: TS2339 [ERROR]: Property 'captureStackTrace' does not exist on type 'ErrorConstructor'.
  Error.captureStackTrace(errorStack);
        ~~~~~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/discordeno/discordeno/12.0.1/src/rest/run_method.ts:36:9
error: Process exited with code 1

```

This is related to [this deno issue](https://github.com/denoland/deno/issues/4702). If its possible to fix this error by including another lib that would solve the issue for me.

**Comment by yeskunall** [comment]
I haven’t had a chance to [use](https://github.com/satyarohith/sift#usage) Sift myself and I don’t think `deployctl` allows you to specify your custom libs (types) using `--libs` (yet)

Does the following not work?:

```ts
// src/mod.ts

interface ErrorConstructor {
  captureStackTrace(error: Object, constructor?: Function): void;
}

class CustomError extends Error {
	constructor(message?: string) {
        super(message);
        Object.setPrototypeOf(this, new.target.prototype);
        this.name = CustomError.name;
    }

	Error.captureStackTrace({}, CustomError);
}

const error = new CustomError();

// error.stack should contain your stack trace
```

Ref: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-2.html#support-for-newtarget

**Comment by kyeotic** [comment]
No, the error is coming from an import deep inside an imported dependency. Deno and deployctl are both able to run this code (if you turn on `--no-check`), so I believe it is an issue with the typechecker not receiving the deno/node types necessary to compile V8 Errors.

**Comment by kt3k** [comment]
@kyeotic What deno version do you use? Because https://github.com/denoland/deno/issues/4702 is resolved in deno repository, I guess upgrading to the latest version of deno might solve the issue.

**Comment by kyeotic** [comment]
I am using deno version 1.12.2

**Comment by lucacasonato** [comment]
Thanks for contributing by opening an issue.

This project is being archived because you can now use `deno run` to run your Deploy scripts locally: https://deno.com/deploy/docs/running-scripts-locally/. As such, I will close this issue.

If you have feedback about Deno Deploy, please open an issue on this repo: https://github.com/denoland/deploy_feedback
