### ISSUE TITLE
Outdated types

### ISSUE THREAD

**Issue by takaeri** [denoland/deployctl#76]
According to the [docs](https://deno.com/deploy/docs/serve-static-assets), `Deno.readFile` is available but when I inspect the `deployctl.d.ts` file, there's no declaration of it at all

**Comment by takaeri** [comment]
![image](https://user-images.githubusercontent.com/89762978/131687654-8822d38b-12f0-42dc-947b-fb23a44524ee.png)
![image](https://user-images.githubusercontent.com/89762978/131687666-a7bc172e-8daf-4753-91d8-6e9c73ded5fd.png)

**Comment by takaeri** [comment]
Closing this since I'm able to fix with some local changes

**Comment by dsherret** [comment]
It's still something that should be resolved. Reopening.

**Comment by takaeri** [comment]
I assume this has been resolved? Closing this

**Comment by dsherret** [comment]
Yup. Now resolved. Thanks!
