### ISSUE TITLE
Deploy error on Dash

### ISSUE THREAD

**Issue by mk0y** [denoland/deployctl#93]
Hi all,

Since I'm not sure where to report this issue, I'll try here.

When I try to link my public github repo, I'm getting following error:

```
The GitHub repository you are requesting was not found, or you do not have access to view it.
```

And the screenshot:

![image](https://user-images.githubusercontent.com/170480/135459770-2c33bdc1-a101-4787-aa43-f32d3d4c5fd2.png)

I created public repo with such code:

```js
addEventListener("fetch", (event) => {

  const resp = new Response("Hello", {
    headers: { "content-type": "text/plain" },
  });

  event.respondWith(resp);
});
```

`deployctl` works well though, but if I want to push to Github deployment is not linked, so I need to manually trigger deployment on dash.deno.com using "Depoy URL" button.

Am I missing something stupid? Or there's a bug right there 🤔

Thank you!
Marko

**Comment by kt3k** [comment]
Thank you for reaching out to us

When the above error happens, do you see the error message panel like the below?

<img width="609" alt="スクリーンショット 2021-10-01 12 57 10" src="https://user-images.githubusercontent.com/613956/135563068-7b821ad9-0a65-4271-b59f-4036e10d17e8.png">

If you see this panel, please click on 'Install GitHub App' button, and install Deno Deploy GitHub App to your repository (in GitHub website)

**Comment by mk0y** [comment]
Perfect, it works, thank you @kt3k. 

I needed to install the GitHub app though but that's normal.

👍
