### ISSUE TITLE
deployment fails with `--no-static` flag

### ISSUE THREAD

**Issue by satyarohith** [denoland/deployctl#96]
```sh
➜ deployctl deploy --project=testhello ./hello.jsx --no-static
✔ Project: testhello
error: The deployment failed: module with specifier 'file:///src/hello.jsx' not found
```

**Comment by lucacasonato** [comment]
That's not a bug. You're not uploading any static files, so you can only use remote specifiers as the entrypoint.

**Comment by satyarohith** [comment]
> That's not a bug. You're not uploading any static files, so you can only use remote specifiers as the entrypoint.

We should probably log that --no-static can only be used with remote specifiers.
